### ISSUE TITLE
Better architecture of code

### ISSUE THREAD

**Issue by RomainGuarinoni** [RomainGuarinoni/mastermind#2]
## Description

Actually, all the typescript code is in one file `/src/index.ts`, it would be better if we create different folder and files to make a better code architecture.

## Tasks

- [x] set up webpack
- [x] Add module to the package json
- [x] update ts config if needed
- [x] update architecture of code public etc...

## External links

- [ A repo with a good configuration](https://github.com/tamani-coding/webpack-typescript-quickstart)
- https://webpack.js.org/guides/typescript/
- https://dimitr.im/web-project-webpack-babel
