### ISSUE TITLE
Make a multiplayer mode

### ISSUE THREAD

**Issue by RomainGuarinoni** [RomainGuarinoni/mastermind#3]
## Description

Create a multiplayer mode when a player could create a private room for 2 player, each one would have to create a secret combination and the first one to find the other combination win the game.

** Describe the feature request**

## Tasks

** describe the road map of the feature**
- [ ] create a backend in express ( need more issues ) 
- [ ] create html page to determine if the player is playing solo or multi
- [ ] add the functionnality to join a room via pasting the link of a room
- [ ] if multiplayer, add the functionality to create a combination for the other player
- [ ] wait until the other player send his combination
- [ ] play the game with the other combination
- [ ] send a msg to the backend when finish
- [ ] display a loose popup if the other finish before( when receiving a msg from the backend)

## External links
- [socket.io](https://socket.io/)
- [room socket.io](https://stackoverflow.com/questions/19150220/creating-rooms-in-socket-io)
-
