### ISSUE TITLE
Make a user documentation

### ISSUE THREAD

**Issue by RomainGuarinoni** [RomainGuarinoni/mastermind#4]
## Description

We have to create a README documention for the user

## Tasks

- [x] Explain the rules of the mastermind
- [x] Explain how to play solo
- [ ] Explain how to create a multiplayer room
- [ ] Explain how to join a multiplayer room
- [ ] Explain the multiplayer rules and how to play it
