### ISSUE TITLE
Create a landing page

### ISSUE THREAD

**Issue by RomainGuarinoni** [RomainGuarinoni/mastermind#41]
## Description
when the user start the website, it should first redirect him to the landing page where he could choose : 

- to play solo
- to create a multi player room
- to join a multiplayer room

## Tasks

- [ ] Add an input to past an room ID 
- [ ] display error of the room does not exist ( result of the backend)
- [ ] Add the game parameters before create a new room
- [ ] Send a backend request to have the ID of the room created
