### ISSUE TITLE
add the possibility for the user to see his game after he win / loose

### ISSUE THREAD

**Issue by RomainGuarinoni** [RomainGuarinoni/mastermind#47]
## Description

Add a possibilty to close the win / loose popup witrhout start a new game to allow the user to see his game. A new button could make the win / loose popup re appear if needed

## Tasks

- [ ] Add a button on win / loose pop up to close it without start a new game
- [ ] Make sure the verify button dont produce weird things when the win / loose popup is reduce
- [ ] Change verify button to see the result instead
