### ISSUE TITLE
Finish developper documentation

### ISSUE THREAD

**Issue by RomainGuarinoni** [RomainGuarinoni/mastermind#5]
## Description

We need to improve the README of the project

We could write it in the wiki of the repository

## Tasks

- [x] Add more details for how to contribute
- [x] Describe the architecture of the project
- [x] Describe the technologies used

## External links

 - Example of a good readme(https://github.com/RomainGuarinoni/findAMusicianBackend)
