### ISSUE TITLE
Create a pop up to display all the best score of the player

### ISSUE THREAD

**Issue by RomainGuarinoni** [RomainGuarinoni/mastermind#52]
## Tasks

- [ ] Create a button to show all the best score ( maybe use a icon like a trophee or smthing)
- [ ] Show all the best time in all category
- [ ] create filter parameters to filter the best score
